# Generated by Django 2.2.6 on 2019-10-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('username', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
    ]
