# Generated by Django 2.2.6 on 2019-11-17 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_auto_20191024_1653'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
